# Generated by Django 3.2.9 on 2021-11-22 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_alter_register_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('code', models.CharField(max_length=10000)),
                ('output', models.CharField(max_length=10000)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.register')),
            ],
        ),
    ]
