# Generated by Django 3.2.9 on 2021-11-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
